const bibleBookList = [
  { id: 1, chapters: 50, title: "Genesis" },
  { id: 2, chapters: 40, title: "Exodus" },
  { id: 3, chapters: 27, title: "Leviticus" },
  { id: 4, chapters: 36, title: "Numbers" },
  { id: 5, chapters: 34, title: "Deuteronomy" },
  { id: 6, chapters: 24, title: "Joshua" },
  { id: 7, chapters: 21, title: "Judges" },
  { id: 8, chapters: 4, title: "Ruth" },
  { id: 9, chapters: 31, title: "1 Samuel" },
  { id: 10, chapters: 24, title: "2 Samuel" },
  { id: 11, chapters: 22, title: "1 Kings" },
  { id: 12, chapters: 25, title: "2 Kings" },
  { id: 13, chapters: 29, title: "1 Chronicles" },
  { id: 14, chapters: 36, title: "2 Chronicles" },
  { id: 15, chapters: 10, title: "Ezra" },
  { id: 16, chapters: 13, title: "Nehemiah" },
  { id: 17, chapters: 10, title: "Esther" },
  { id: 18, chapters: 42, title: "Job" },
  { id: 19, chapters: 150, title: "Psalms" },
  { id: 20, chapters: 31, title: "Proverbs" },
  { id: 21, chapters: 12, title: "Ecclesiastes" },
  { id: 22, chapters: 8, title: "Song of Solomon" },
  { id: 23, chapters: 66, title: "Isaiah" },
  { id: 24, chapters: 52, title: "Jeremiah" },
  { id: 25, chapters: 5, title: "Lamentations" },
  { id: 26, chapters: 48, title: "Ezekiel" },
  { id: 27, chapters: 12, title: "Daniel" },
  { id: 28, chapters: 14, title: "Hosea" },
  { id: 29, chapters: 3, title: "Joel" },
  { id: 30, chapters: 9, title: "Amos" },
  { id: 31, chapters: 1, title: "Obadiah" },
  { id: 32, chapters: 4, title: "Jonah" },
  { id: 33, chapters: 7, title: "Micah" },
  { id: 34, chapters: 3, title: "Nahum" },
  { id: 35, chapters: 3, title: "Habakkuk" },
  { id: 36, chapters: 3, title: "Zephaniah" },
  { id: 37, chapters: 2, title: "Haggai" },
  { id: 38, chapters: 14, title: "Zechariah" },
  { id: 39, chapters: 4, title: "Malachi" },
  { id: 40, chapters: 28, title: "Matthew" },
  { id: 41, chapters: 16, title: "Mark" },
  { id: 42, chapters: 24, title: "Luke" },
  { id: 43, chapters: 21, title: "John" },
  { id: 44, chapters: 28, title: "Acts" },
  { id: 45, chapters: 16, title: "Romans" },
  { id: 46, chapters: 16, title: "1 Corinthians" },
  { id: 47, chapters: 13, title: "2 Corinthians" },
  { id: 48, chapters: 6, title: "Galatians" },
  { id: 49, chapters: 6, title: "Ephesians" },
  { id: 50, chapters: 4, title: "Philippians" },
  { id: 51, chapters: 4, title: "Colossians" },
  { id: 52, chapters: 5, title: "1 Thessalonians" },
  { id: 53, chapters: 3, title: "2 Thessalonians" },
  { id: 54, chapters: 6, title: "1 Timothy" },
  { id: 55, chapters: 4, title: "2 Timothy" },
  { id: 56, chapters: 3, title: "Titus" },
  { id: 57, chapters: 1, title: "Philemon" },
  { id: 58, chapters: 13, title: "Hebrews" },
  { id: 59, chapters: 5, title: "James" },
  { id: 60, chapters: 5, title: "1 Peter" },
  { id: 61, chapters: 3, title: "2 Peter" },
  { id: 62, chapters: 5, title: "1 John" },
  { id: 63, chapters: 1, title: "2 John" },
  { id: 64, chapters: 1, title: "3 John" },
  { id: 65, chapters: 1, title: "Jude" },
  { id: 66, chapters: 22, title: "Revelation" }
];

export default bibleBookList;
